models:
  gpt-5-nano:
    model_url: "https://api.openai.com/v1/chat/completions"
    model_name: "gpt-5-nano"
    #api_key: "${OPENAI_API_KEY}"
    api_key: "${SECRET_OPENAI_API_KEY}"
    compliance_level: "External"
  gpt-5.1:
    model_url: "https://api.openai.com/v1/chat/completions"
    model_name: "gpt-5.1"
    #api_key: "${OPENAI_API_KEY}"
    api_key: "${SECRET_OPENAI_API_KEY}"
    compliance_level: "External"
  cerebras-gpt-oss-120b:
    model_url: "https://api.cerebras.ai/v1"
    model_name: "gpt-oss-120b"
    #api_key: "${CEREBRAS_API_KEY}"
    api_key: "${SECRET_CEREBRAS_API_KEY}"
    compliance_level: "External"
  argonne-gpt-oss-120b:
    model_url: "https://inference-api.alcf.anl.gov/resource_server/metis/api/v1"
    model_name: "openai/gpt-oss-120b-131072"
    api_key: "${SECRET_ANL_API_KEY}"
    compliance_level: "External"
